version: "3.3"

services:

  activemq:
    image: rmohr/activemq:5.15.5
    ports:
      - "61616:61616"
      - "8161:8161"

  localstack:
    image: localstack/localstack:0.14.5
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=sns,sqs,s3
